<a name="top"></a>
# Python Workshop 3
We will look at [NumPy](http://www.numpy.org/) and [Pandas](https://pandas.pydata.org/), which are two of the most popular packages for data analysts these days.

* [NumPy](#numpy) is the homogeneous multidimensional array, which is perfect for predictive analysis.
* [Pandas](#pandas) provides an easy-to-use data structures, which is great for handling data.

-----
<a name="numpy"></a>
## NumPy
NumPy’s main object is the homogeneous multidimensional array (a N-dimensional hypervolume whose elements, usually numbers, are all of the same type). NumPy’s array class is called `ndarray`. Here we will cover:
* Array Creation
* Basic Operations
* Indexing, Slicing and Iterating
* Shape Manipulation
* Copies

More details [here](https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html).

### Array Creation
First, we need to create the `ndarray`. There are several ways to create arrays.

In [1]:
import numpy as np
a = np.array([2,3,4])
print('a={}\ntype={}'.format(a, type(a)))
b = np.array([1.2, 3.5, 5.1])
print('b=',b)
c = np.zeros((2,4))
print('c=',c)
d = np.ones((2,3,4))
print('d=',d)
e = np.empty((2,3))
print('e=',e)

a=[2 3 4]
type=<class 'numpy.ndarray'>
b= [1.2 3.5 5.1]
c= [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
d= [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
e= [[ 7.48462372e-157  6.90955252e-310  6.90952868e-310]
 [-6.63948296e+042  6.90955252e-310  6.90952868e-310]]


Notice how NumPy displays array (in NumPy dimensions are called axes):
* The last axis is printed from left to right,
* The second-to-last is printed from top to bottom,
* The rest are also printed from top to bottom, with each slice separated from the next by an empty line.

You can create sequences of numbers as well

In [2]:
f = np.arange(10, 30, 5)
print('arange=', f)
g = np.linspace(0, 2, 9)
print('linspace=', g)
h = np.random.random((3,4))
print('random=', h)

arange= [10 15 20 25]
linspace= [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
random= [[0.31564847 0.15635778 0.87617335 0.16654728]
 [0.12224166 0.37367313 0.43230783 0.40583853]
 [0.77670007 0.84093839 0.52490493 0.59152527]]


`ndarray` has a number of attributes.

In [3]:
print('a=',a)
print('a.ndim=',a.ndim)
print('a.shape=',a.shape)
print('a.size=',a.size)
print('a.dtype=',a.dtype)

a= [2 3 4]
a.ndim= 1
a.shape= (3,)
a.size= 3
a.dtype= int64


### Basic Operations
Arithmetic operators on arrays apply elementwise.

In [4]:
print('a=',a)
print('b=',b)
print('a-b=',a-b)

a= [2 3 4]
b= [1.2 3.5 5.1]
a-b= [ 0.8 -0.5 -1.1]


In [5]:
print(a**2)
print(np.sqrt(a))
print(b>3)

[ 4  9 16]
[1.41421356 1.73205081 2.        ]
[False  True  True]


Many unary operations, such as the sum of all the elements in the array, are implemented as methods of the `ndarray` class.

In [6]:
print(a.sum())
print(a.mean())
print(a.std())
print(a.min(), a.max())

9
3.0
0.816496580927726
2 4


### Indexing, Slicing and Iterating
**Indexing** and **slicing** are similar to list. Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [7]:
print('a=',a)
print('a[1]=',a[1])
print('a[1:]=',a[1:])

a= [2 3 4]
a[1]= 3
a[1:]= [3 4]


In [8]:
print('e=',e)
print('e[0,1]=',e[0,1])
print('e[:,1]=',e[:,1])
print('e[0,0:2]=',e[0,0:2])

e= [[ 7.48462372e-157  6.90955252e-310  6.90952868e-310]
 [-6.63948296e+042  6.90955252e-310  6.90952868e-310]]
e[0,1]= 6.90955251618815e-310
e[:,1]= [6.90955252e-310 6.90955252e-310]
e[0,0:2]= [7.48462372e-157 6.90955252e-310]


When fewer indices are provided than the number of axes, the missing indices are considered complete slices.

In [9]:
print('d=',d)
print('d[1]=',d[1])
print('d[...,3]=', d[...,3])

d= [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
d[1]= [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
d[...,3]= [[1. 1. 1.]
 [1. 1. 1.]]


**Iterating** over multidimensional arrays is done with respect to the first axis:

In [10]:
for row in e:
    print('row=',row)

row= [7.48462372e-157 6.90955252e-310 6.90952868e-310]
row= [-6.63948296e+042  6.90955252e-310  6.90952868e-310]


### Shape Manipulation
You can change the shape of an array.

In [11]:
print('h=',h)
print(h.shape)

h= [[0.31564847 0.15635778 0.87617335 0.16654728]
 [0.12224166 0.37367313 0.43230783 0.40583853]
 [0.77670007 0.84093839 0.52490493 0.59152527]]
(3, 4)


In [12]:
print('reshape=',h.reshape(6,2))

reshape= [[0.31564847 0.15635778]
 [0.87617335 0.16654728]
 [0.12224166 0.37367313]
 [0.43230783 0.40583853]
 [0.77670007 0.84093839]
 [0.52490493 0.59152527]]


In [13]:
print('transpose=',h.T)

transpose= [[0.31564847 0.12224166 0.77670007]
 [0.15635778 0.37367313 0.84093839]
 [0.87617335 0.43230783 0.52490493]
 [0.16654728 0.40583853 0.59152527]]


### Copies
**No Copy at All** (passing-by-reference): Simple assignments make no copy of array objects or of their data.

In [14]:
a = np.arange(12)
b = a
print('a=',a)
print(b is a)
b[0] = 100
print('a=',a)

a= [ 0  1  2  3  4  5  6  7  8  9 10 11]
True
a= [100   1   2   3   4   5   6   7   8   9  10  11]


**Deep Copy** (passing-by-value): The `copy` method makes a complete copy of the array and its data.

In [15]:
d = a.copy()
print(d is a)
d[0] = 50
print('a=',a)
print('d=',d)

False
a= [100   1   2   3   4   5   6   7   8   9  10  11]
d= [50  1  2  3  4  5  6  7  8  9 10 11]


[[top](#top)]

----

## <a name="pandas"></a> Pandas
pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

Pandas handles data through
* Series for 1D data
* Data Frame for 2D data

### Series
Series is a one-dimensional labeled array capable of holding data of any type (integer, string, float, python objects, etc.).

In [16]:
import pandas as pd
s = pd.Series([1,3,5,'str',6.1])
s

0      1
1      3
2      5
3    str
4    6.1
dtype: object

In [17]:
s = pd.Series(range(3))
s

0    0
1    1
2    2
dtype: int64

### DataFrame
A Data frame is a 2D data structure, where data is aligned in a tabular fashion in rows and columns.

In [18]:
df1 = pd.DataFrame(np.random.randn(3,4), columns=['A','B','C','D'])
print(df1)

          A         B         C         D
0 -0.831024 -0.424219  0.673681  0.155314
1 -0.031966 -0.151838  0.163245  2.802225
2 -2.091403  0.568633 -0.409543  0.411693


In [19]:
df1

A         B         C         D
0 -0.831024 -0.424219  0.673681  0.155314
1 -0.031966 -0.151838  0.163245  2.802225
2 -2.091403  0.568633 -0.409543  0.411693

In [20]:
df2 = pd.DataFrame({'A':1, 'B':np.arange(3), 'C':'Hello'})
df2

A  B      C
0  1  0  Hello
1  1  1  Hello
2  1  2  Hello

In [21]:
df1 = pd.DataFrame(np.random.randn(10,5), columns=['A','B','C','D', 'E'])
df1

A         B         C         D         E
0  0.570089  0.548386 -0.341706  0.153371 -0.144586
1  0.519748  0.621356 -0.156301 -1.051854 -0.111745
2  0.092494 -1.079553  1.056655  0.366991 -0.262277
3 -0.427414 -1.636610  0.521134 -0.012285  0.553718
4  0.873560 -0.871419 -0.185396  1.069738  0.696834
5 -0.376521 -0.322117  0.630230 -0.205193 -0.162689
6  0.139516 -1.778101  0.396926 -0.831885 -0.855318
7  1.280675  2.213081  0.359461  1.959266  2.342834
8  0.667087 -0.918614  0.130699 -0.938855 -0.677521
9 -0.280303  0.371691  1.160210  0.408257  1.103329

In [22]:
df1.head(3)

A         B         C         D         E
0  0.570089  0.548386 -0.341706  0.153371 -0.144586
1  0.519748  0.621356 -0.156301 -1.051854 -0.111745
2  0.092494 -1.079553  1.056655  0.366991 -0.262277

In [23]:
df1.tail(3)

A         B         C         D         E
7  1.280675  2.213081  0.359461  1.959266  2.342834
8  0.667087 -0.918614  0.130699 -0.938855 -0.677521
9 -0.280303  0.371691  1.160210  0.408257  1.103329

In [24]:
df1.index

RangeIndex(start=0, stop=10, step=1)

In [25]:
df1.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [26]:
df1.values

array([[ 0.57008875,  0.54838635, -0.34170567,  0.153371  , -0.1445856 ],
       [ 0.51974762,  0.6213558 , -0.15630138, -1.05185354, -0.11174529],
       [ 0.09249364, -1.07955328,  1.05665538,  0.36699134, -0.2622767 ],
       [-0.42741355, -1.63660983,  0.52113379, -0.01228513,  0.55371775],
       [ 0.87356014, -0.87141926, -0.185396  ,  1.06973756,  0.69683403],
       [-0.37652052, -0.32211731,  0.63023007, -0.20519325, -0.16268891],
       [ 0.13951554, -1.77810071,  0.39692567, -0.83188463, -0.85531812],
       [ 1.28067505,  2.21308138,  0.35946089,  1.95926649,  2.34283437],
       [ 0.66708749, -0.91861431,  0.13069866, -0.93885491, -0.67752097],
       [-0.2803029 ,  0.37169052,  1.16021041,  0.40825731,  1.1033287 ]])

In [27]:
type(df1.values)

numpy.ndarray

### Getting Data In/Out

#### CSV
**CSV** (comma separated values) file is a text file in which the values in the
columns are separated by a comma.

CSV is preferred because of its simplicity, and it can be used with any spreadsheet program.

In [28]:
df3 = pd.read_csv('customer.csv')
df3

customer_id first_name   last_name                email  \
0            1     George  Washington  gwashington@usa.gov   
1            2       John       Adams       jadams@usa.gov   
2            3     Thomas   Jefferson   tjefferson@usa.gov   
3            4      James     Madison     jmadison@usa.gov   
4            5      James      Monroe      jmonroe@usa.gov   

                     address             city state    zip  balance  
0         3200 Mt Vernon Hwy     Mount Vernon    VA  22121     1000  
1            1250 Hancock St           Quincy    MA   2169      500  
2  931 Thomas Jefferson Pkwy  Charlottesville    VA  22902     2500  
3     11350 Constitution Hwy           Orange    VA  22960     9000  
4     2050 James Monroe Pkwy  Charlottesville    VA  22902     1756

In [29]:
df3.to_csv('customer2.csv', header=False, index=False, float_format='%.6f')

#### JSON

**JSON** (JavaScript Object Notation) stores data as text in human-readable format. JSON object is a key-value data format that is typically rendered in curly brackets. Arrays use square brackets.

JSON is good for NoSQL data since its structure is more flexible and can handle tabular format.

In [30]:
!cat test.json
#!type test.json
df4 = pd.read_json('test.json')
df4

{
    "fruit": ["Apple", "Banana", "Orange", "Peach", "Pear"],
    "size": ["Large", "Medium", "Small", "Small", "Large"],
    "color": ["Red", "Yellow", "Orange", "Pink", "Green"]
}


fruit    size   color
0   Apple   Large     Red
1  Banana  Medium  Yellow
2  Orange   Small  Orange
3   Peach   Small    Pink
4    Pear   Large   Green

In [31]:
json_str = df4.to_json(orient='records', lines=True)
print(json_str)
print(type(json_str))

{"fruit":"Apple","size":"Large","color":"Red"}
{"fruit":"Banana","size":"Medium","color":"Yellow"}
{"fruit":"Orange","size":"Small","color":"Orange"}
{"fruit":"Peach","size":"Small","color":"Pink"}
{"fruit":"Pear","size":"Large","color":"Green"}
<class 'str'>


#### Excel

Excel is the best spreadsheet software package available.

In [32]:
df5 = pd.read_excel('test.xlsx', index_col=0)
print(df5)

            first_name   last_name                email  \
customer_id                                               
1               George  Washington  gwashington@usa.gov   
2                 John       Adams       jadams@usa.gov   
3               Thomas   Jefferson   tjefferson@usa.gov   
4                James     Madison     jmadison@usa.gov   
5                James      Monroe      jmonroe@usa.gov   

                               address             city state    zip  
customer_id                                                           
1                   3200 Mt Vernon Hwy     Mount Vernon    VA  22121  
2                      1250 Hancock St           Quincy    MA   2169  
3            931 Thomas Jefferson Pkwy  Charlottesville    VA  22902  
4               11350 Constitution Hwy           Orange    VA  22960  
5               2050 James Monroe Pkwy  Charlottesville    VA  22902  


In [33]:
xl = pd.ExcelFile('test.xlsx')
for i, name in enumerate(xl.sheet_names):
    df = xl.parse(name, index_col=0)
    print('\nDataFrame', i)
    print(df)


DataFrame 0
            first_name   last_name                email  \
customer_id                                               
1               George  Washington  gwashington@usa.gov   
2                 John       Adams       jadams@usa.gov   
3               Thomas   Jefferson   tjefferson@usa.gov   
4                James     Madison     jmadison@usa.gov   
5                James      Monroe      jmonroe@usa.gov   

                               address             city state    zip  
customer_id                                                           
1                   3200 Mt Vernon Hwy     Mount Vernon    VA  22121  
2                      1250 Hancock St           Quincy    MA   2169  
3            931 Thomas Jefferson Pkwy  Charlottesville    VA  22902  
4               11350 Constitution Hwy           Orange    VA  22960  
5               2050 James Monroe Pkwy  Charlottesville    VA  22902  

DataFrame 1
                   order_date   amount  customer_id
order_id   

In [34]:
with pd.ExcelWriter('test2.xlsx') as writer:
    df2.to_excel(writer, sheet_name='Sheet1')
    df4.to_excel(writer, sheet_name='Sheet2')

For more details about Pandas I/O see at https://pandas.pydata.org/pandas-docs/stable/reference/io.html

#### Convert Between NumPy and Pandas

You can convert between Pandas DataFrame/Series and NumPy ndarray very easily

In [35]:
a1 = np.array(df1)
a1

array([[ 0.57008875,  0.54838635, -0.34170567,  0.153371  , -0.1445856 ],
       [ 0.51974762,  0.6213558 , -0.15630138, -1.05185354, -0.11174529],
       [ 0.09249364, -1.07955328,  1.05665538,  0.36699134, -0.2622767 ],
       [-0.42741355, -1.63660983,  0.52113379, -0.01228513,  0.55371775],
       [ 0.87356014, -0.87141926, -0.185396  ,  1.06973756,  0.69683403],
       [-0.37652052, -0.32211731,  0.63023007, -0.20519325, -0.16268891],
       [ 0.13951554, -1.77810071,  0.39692567, -0.83188463, -0.85531812],
       [ 1.28067505,  2.21308138,  0.35946089,  1.95926649,  2.34283437],
       [ 0.66708749, -0.91861431,  0.13069866, -0.93885491, -0.67752097],
       [-0.2803029 ,  0.37169052,  1.16021041,  0.40825731,  1.1033287 ]])

In [36]:
a1.dtype

dtype('float64')

In [37]:
a2 = np.array(df2)
a2

array([[1, 0, 'Hello'],
       [1, 1, 'Hello'],
       [1, 2, 'Hello']], dtype=object)

In [38]:
df2.values

array([[1, 0, 'Hello'],
       [1, 1, 'Hello'],
       [1, 2, 'Hello']], dtype=object)

In [39]:
pd.DataFrame(a1)

0         1         2         3         4
0  0.570089  0.548386 -0.341706  0.153371 -0.144586
1  0.519748  0.621356 -0.156301 -1.051854 -0.111745
2  0.092494 -1.079553  1.056655  0.366991 -0.262277
3 -0.427414 -1.636610  0.521134 -0.012285  0.553718
4  0.873560 -0.871419 -0.185396  1.069738  0.696834
5 -0.376521 -0.322117  0.630230 -0.205193 -0.162689
6  0.139516 -1.778101  0.396926 -0.831885 -0.855318
7  1.280675  2.213081  0.359461  1.959266  2.342834
8  0.667087 -0.918614  0.130699 -0.938855 -0.677521
9 -0.280303  0.371691  1.160210  0.408257  1.103329

In [40]:
pd.Series(a2[:,1])

0    0
1    1
2    2
dtype: object

[[top](#top)]

----